# -*- coding: utf-8 -*-
"""Intern44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14muYanStJOUrzzAiQg3FuwDwhEG24C5S
"""

!pip install -qqq nibabel scikit-image tqdm torch torchvision -q
!apt-get install -qq dcm2niix tree unrar

import os, json, zipfile, shutil
import numpy as np
import nibabel as nib
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from skimage.metrics import structural_similarity as ssim_fn
from skimage.metrics import peak_signal_noise_ratio as psnr_fn
from tqdm import tqdm
import random
import subprocess

BASE_DIR = "/content/data"

DIRS = {
    "brats": f"{BASE_DIR}/BraTS",
    "mambamorph": f"{BASE_DIR}/MambaMorph",
    "pct_mri": f"{BASE_DIR}/PCT-MRI",
    "remind": f"{BASE_DIR}/ReMIND2Reg",
    "synthrad": f"{BASE_DIR}/SynthRAD",
}

for d in DIRS.values():
    os.makedirs(d, exist_ok=True)

print("Directories created:")
print(DIRS)

synthrad_files = [
    {
        "name": "Task1.zip",
        "url": "https://zenodo.org/records/7260705/files/Task1.zip?download=1",
    },
]

save_dir = DIRS["synthrad"]

for file_info in synthrad_files:
    zip_path = os.path.join(save_dir, file_info["name"])
    extract_dir = os.path.join(save_dir, file_info["name"].replace(".zip", ""))

    if not os.path.exists(zip_path):
        print(f"Downloading {file_info['name']} ...")
        subprocess.run([
            "wget",
            "-c",
            "-O",
            zip_path,
            file_info["url"]
        ], check=True)
        print(f"Done: {file_info['name']}")
    else:
        print(f"Already exists: {file_info['name']}")

    os.makedirs(extract_dir, exist_ok=True)

    print(f"Extracting {file_info['name']} to {extract_dir} ...")
    subprocess.run([
        "unzip",
        "-q",
        zip_path,
        "-d",
        extract_dir
    ], check=True)
    print(f"Extracted: {file_info['name']}\n")

!unrar x /content/Task1_val.rar /content/data/SynthRAD/

CFG = {
    # paths
    'task1_train'      : '/content/data/SynthRAD/Task1/Task1/brain',
    'task1_val'        : '/content/data/SynthRAD/Task1_val/Task1/brain',
    'stats_path'       : '/content/data/SynthRAD/normalisation_stats.json',
    'cache_dir'        : '/content/data/SynthRAD/cache_2d',
    'cache_zip'        : '/content/data/SynthRAD/cache_2d.zip',
    'ckpt_dir'         : '/content/data/SynthRAD/checkpoints',

    # preprocessing
    'ct_clip_min'      : -1000.0,
    'ct_clip_max'      :  1000.0,
    'min_mask_coverage':  0.10,

    # dataloader
    'batch_size'       : 8,
    'num_workers'      : 2,
    'plane'            : 'axial',

    # training mode
    'spatial_mode'     : '2D',
    'model_type'       : 'unet',
    'loss_type'        : 'l1',

    # model
    'unet_base_ch'     : 64,
    'in_ch'            : 1,
    'out_ch'           : 1,

    # training
    'lr'               : 2e-4,
    'epochs'           : 1000,
    'val_every'        : 5,
    'save_every'       : 10,
    'device'           : 'cuda' if torch.cuda.is_available() else 'cpu',

    # reproducibility
    'seed'             : 15,
    'train_val_split'  : 0.9,

    'early_stopping_patience': 15,
}

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(CFG['seed'])
os.makedirs(CFG['cache_dir'], exist_ok=True)
os.makedirs(CFG['ckpt_dir'],  exist_ok=True)
print(f"Device : {CFG['device']}")
print(f"Seed   : {CFG['seed']}")

# import nibabel as nib
# import os
# import numpy as np
# from tqdm import tqdm

# shapes = []
# for p in tqdm(train_patients, desc='Scanning shapes'):
#     vol = nib.load(os.path.join(p['path'], 'mr.nii.gz')).get_fdata(dtype=np.float32)
#     shapes.append(vol.shape)

# shapes = np.array(shapes)
# print(f'X range: {shapes[:,0].min()} - {shapes[:,0].max()}')
# print(f'Y range: {shapes[:,1].min()} - {shapes[:,1].max()}')
# print(f'Z range: {shapes[:,2].min()} - {shapes[:,2].max()}')
# print(f'Most common X: {np.bincount(shapes[:,0]).argmax()}')
# print(f'Most common Y: {np.bincount(shapes[:,1]).argmax()}')

"""# 3.Preprocessing"""

def compute_and_save_stats(train_root, stats_path, ct_clip_min, ct_clip_max):
    print('Stats JSON not found. Recomputing from scratch...')

    def scan(root):
        patients = []
        for pid in sorted(os.listdir(root)):
            if pid == 'overview':
                continue
            pdir = os.path.join(root, pid)
            if not os.path.isdir(pdir):
                continue
            if 'ct.nii.gz' not in os.listdir(pdir):
                continue
            patients.append({'patient_id': pid, 'path': pdir})
        return patients

    patients = scan(train_root)
    print(f'Found {len(patients)} patients for stats computation.')

    sum_v, sum_sq_v, n_v = 0.0, 0.0, 0
    mr_p01_list, mr_p99_list = [], []

    for p in tqdm(patients, desc='Computing stats'):
        ct_vol = nib.load(os.path.join(p['path'], 'ct.nii.gz')).get_fdata(
            dtype=np.float32, caching='unchanged')
        mr_vol = nib.load(os.path.join(p['path'], 'mr.nii.gz')).get_fdata(
            dtype=np.float32, caching='unchanged')
        mask_vol = nib.load(os.path.join(p['path'], 'mask.nii.gz')).get_fdata(
            dtype=np.float32, caching='unchanged')

        ct_clipped = np.clip(ct_vol, ct_clip_min, ct_clip_max)
        sum_v    += float(ct_clipped.sum())
        sum_sq_v += float((ct_clipped ** 2).sum())
        n_v      += ct_clipped.size

        brain_voxels = mr_vol[mask_vol > 0]
        if brain_voxels.size == 0:
            brain_voxels = mr_vol[mr_vol > 0]
        mr_p01_list.append(float(np.percentile(brain_voxels, 1)))
        mr_p99_list.append(float(np.percentile(brain_voxels, 99)))

    ct_mean = float(sum_v / n_v)
    ct_std  = float(np.sqrt(sum_sq_v / n_v - ct_mean ** 2))

    stats = {
        'ct_clip_min'    : float(ct_clip_min),
        'ct_clip_max'    : float(ct_clip_max),
        'ct_global_mean' : ct_mean,
        'ct_global_std'  : ct_std,
        'mr_p01_mean'    : float(np.mean(mr_p01_list)),
        'mr_p99_mean'    : float(np.mean(mr_p99_list)),
        'mr_p01_std'     : float(np.std(mr_p01_list)),
        'mr_p99_std'     : float(np.std(mr_p99_list)),
        'n_patients'     : len(patients),
    }

    with open(stats_path, 'w') as f:
        json.dump(stats, f, indent=2)

    print(f'Stats saved to: {stats_path}')
    print(f'CT  mean: {ct_mean:.4f} | std: {ct_std:.4f}')
    print(f'MR  p01 mean: {stats["mr_p01_mean"]:.4f} | p99 mean: {stats["mr_p99_mean"]:.4f}')
    return stats


if os.path.exists(CFG['stats_path']):
    with open(CFG['stats_path']) as f:
        NORM_STATS = json.load(f)
    print(f'Stats loaded from: {CFG["stats_path"]}')
else:
    NORM_STATS = compute_and_save_stats(
        CFG['task1_train'],
        CFG['stats_path'],
        CFG['ct_clip_min'],
        CFG['ct_clip_max'],
    )

print(f'CT  clip [{NORM_STATS["ct_clip_min"]}, {NORM_STATS["ct_clip_max"]}] '
      f'-> mean={NORM_STATS["ct_global_mean"]:.4f}, std={NORM_STATS["ct_global_std"]:.4f}')
print(f'MR  p99 mean={NORM_STATS["mr_p99_mean"]:.4f} +/- {NORM_STATS["mr_p99_std"]:.4f}')


def preprocess_mr(vol, mask=None):
    brain_voxels = vol[mask > 0] if mask is not None else vol[vol > 0]
    if brain_voxels.size == 0:
        brain_voxels = vol
    p01 = float(np.percentile(brain_voxels, 1))
    p99 = float(np.percentile(brain_voxels, 99))
    vol = np.clip(vol, p01, p99)
    vol = (vol - p01) / (p99 - p01 + 1e-8)
    return vol.astype(np.float32)

def preprocess_ct(vol):
    vol = np.clip(vol, CFG['ct_clip_min'], CFG['ct_clip_max'])
    vol = (vol - NORM_STATS['ct_global_mean']) / (NORM_STATS['ct_global_std'] + 1e-8)
    return vol.astype(np.float32)

def postprocess_ct(vol):
    vol = vol * NORM_STATS['ct_global_std'] + NORM_STATS['ct_global_mean']
    vol = np.clip(vol, CFG['ct_clip_min'], CFG['ct_clip_max'])
    return vol.astype(np.float32)

print('Preprocessing functions defined.')

"""# 4.Pre-extract and cache slices"""

def scan_patients(root, require_ct=True):
    patients = []
    for pid in sorted(os.listdir(root)):
        if pid == 'overview':
            continue
        pdir = os.path.join(root, pid)
        if not os.path.isdir(pdir):
            continue
        files = os.listdir(pdir)
        if require_ct and 'ct.nii.gz' not in files:
            continue
        patients.append({'patient_id': pid, 'path': pdir})
    return patients

def cache_patient_slices(patient, cache_dir, min_mask_coverage, plane='axial'):
    pid   = patient['patient_id']
    pdir  = patient['path']
    p_cache_dir = os.path.join(cache_dir, pid)
    os.makedirs(p_cache_dir, exist_ok=True)

    mr_vol   = nib.load(os.path.join(pdir, 'mr.nii.gz')).get_fdata(dtype=np.float32)
    ct_vol   = nib.load(os.path.join(pdir, 'ct.nii.gz')).get_fdata(dtype=np.float32)
    mask_vol = nib.load(os.path.join(pdir, 'mask.nii.gz')).get_fdata(dtype=np.float32)

    mr_proc   = preprocess_mr(mr_vol, mask=mask_vol)
    ct_proc   = preprocess_ct(ct_vol)
    mask_proc = (mask_vol > 0).astype(np.float32)

    if plane == 'axial':
        n_slices = mr_proc.shape[2]
        get_slice = lambda v, i: v[:, :, i]
    elif plane == 'coronal':
        n_slices = mr_proc.shape[1]
        get_slice = lambda v, i: v[:, i, :]
    else:
        n_slices = mr_proc.shape[0]
        get_slice = lambda v, i: v[i, :, :]

    saved = 0
    for i in range(n_slices):
        mask_sl = get_slice(mask_proc, i)
        coverage = mask_sl.mean()
        if coverage < min_mask_coverage:
            continue
        mr_sl = get_slice(mr_proc, i)
        ct_sl = get_slice(ct_proc, i)
        packed = np.stack([mr_sl, ct_sl, mask_sl], axis=0).astype(np.float32)  # (3, H, W)
        np.save(os.path.join(p_cache_dir, f'{i:04d}.npy'), packed)
        saved += 1

    return saved

train_patients = scan_patients(CFG['task1_train'], require_ct=True)
print(f'Found {len(train_patients)} training patients.')

already_cached = [
    p for p in train_patients
    if os.path.isdir(os.path.join(CFG['cache_dir'], p['patient_id']))
    and len(os.listdir(os.path.join(CFG['cache_dir'], p['patient_id']))) > 0
]

if len(already_cached) == len(train_patients):
    print('Cache already complete, skipping.')
else:
    total_slices = 0
    for p in tqdm(train_patients, desc='Caching slices'):
        pid_cache = os.path.join(CFG['cache_dir'], p['patient_id'])
        if os.path.isdir(pid_cache) and len(os.listdir(pid_cache)) > 0:
            total_slices += len(os.listdir(pid_cache))
            continue
        n = cache_patient_slices(p, CFG['cache_dir'], CFG['min_mask_coverage'], CFG['plane'])
        total_slices += n
    print(f'Cached {total_slices} slices from {len(train_patients)} patients.')

# count total cached slices
total = sum(
    len(os.listdir(os.path.join(CFG['cache_dir'], p['patient_id'])))
    for p in train_patients
    if os.path.isdir(os.path.join(CFG['cache_dir'], p['patient_id']))
)
print(f'Total slices in cache: {total}')

"""# 6.Data Loader"""

TARGET_SIZE = 320

def pad_to_target(arr, target_h, target_w):
    h, w = arr.shape
    pad_top    = (target_h - h) // 2
    pad_bottom = target_h - h - pad_top
    pad_left   = (target_w - w) // 2
    pad_right  = target_w - w - pad_left
    return np.pad(arr, ((pad_top, pad_bottom), (pad_left, pad_right)), mode='constant', constant_values=0)

class SliceDataset2D(Dataset):
    def __init__(self, cache_dir, patient_list, target_size=TARGET_SIZE):
        self.slices      = []
        self.target_size = target_size
        for p in patient_list:
            pid   = p['patient_id']
            p_dir = os.path.join(cache_dir, pid)
            if not os.path.isdir(p_dir):
                continue
            for fname in sorted(os.listdir(p_dir)):
                if fname.endswith('.npy'):
                    self.slices.append(os.path.join(p_dir, fname))
        print(f'Dataset: {len(self.slices)} slices from {len(patient_list)} patients.')

    def __len__(self):
        return len(self.slices)

    def __getitem__(self, idx):
        packed = np.load(self.slices[idx])           # (3, H, W)
        mr     = pad_to_target(packed[0], self.target_size, self.target_size)
        ct     = pad_to_target(packed[1], self.target_size, self.target_size)
        mask   = pad_to_target(packed[2], self.target_size, self.target_size)
        mr   = torch.from_numpy(mr).unsqueeze(0)     # (1, 320, 320)
        ct   = torch.from_numpy(ct).unsqueeze(0)
        mask = torch.from_numpy(mask).unsqueeze(0)
        return mr, ct, mask

class SliceDataset25D(Dataset):
    def __init__(self, *args, **kwargs):
        raise NotImplementedError('2.5D dataset not yet implemented.')

class PatchDataset3D(Dataset):
    def __init__(self, *args, **kwargs):
        raise NotImplementedError('3D patch dataset not yet implemented.')


train_patients = scan_patients(CFG['task1_train'], require_ct=True)

rng      = random.Random(CFG['seed'])
shuffled = train_patients.copy()
rng.shuffle(shuffled)

split_idx     = int(CFG['train_val_split'] * len(shuffled))
tr_patients   = shuffled[:split_idx]
hold_patients = shuffled[split_idx:]

print(f'Train patients : {len(tr_patients)}')
print(f'Hold  patients : {len(hold_patients)}')

if CFG['spatial_mode'] == '2D':
    tr_dataset   = SliceDataset2D(CFG['cache_dir'], tr_patients)
    hold_dataset = SliceDataset2D(CFG['cache_dir'], hold_patients)
else:
    raise NotImplementedError(f"spatial_mode '{CFG['spatial_mode']}' not yet implemented.")

use_pin_memory = CFG['device'] == 'cuda'

tr_loader   = DataLoader(tr_dataset,   batch_size=CFG['batch_size'], shuffle=True,
                         num_workers=CFG['num_workers'], pin_memory=use_pin_memory)
hold_loader = DataLoader(hold_dataset, batch_size=CFG['batch_size'], shuffle=False,
                         num_workers=CFG['num_workers'], pin_memory=use_pin_memory)

print(f'Train loader : {len(tr_loader)} batches')
print(f'Hold  loader : {len(hold_loader)} batches')

"""# 7.Model"""

# Cell 7
class ConvBlock(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.InstanceNorm2d(out_ch),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.InstanceNorm2d(out_ch),
            nn.LeakyReLU(0.2, inplace=True),
        )
    def forward(self, x):
        return self.block(x)

class UNet(nn.Module):
    def __init__(self, in_ch=1, out_ch=1, base_ch=64):
        super().__init__()
        b = base_ch
        self.enc1 = ConvBlock(in_ch, b)
        self.enc2 = ConvBlock(b,     b*2)
        self.enc3 = ConvBlock(b*2,   b*4)
        self.enc4 = ConvBlock(b*4,   b*8)
        self.bottleneck = ConvBlock(b*8, b*16)
        self.up4  = nn.ConvTranspose2d(b*16, b*8,  2, stride=2)
        self.dec4 = ConvBlock(b*16, b*8)
        self.up3  = nn.ConvTranspose2d(b*8,  b*4,  2, stride=2)
        self.dec3 = ConvBlock(b*8,  b*4)
        self.up2  = nn.ConvTranspose2d(b*4,  b*2,  2, stride=2)
        self.dec2 = ConvBlock(b*4,  b*2)
        self.up1  = nn.ConvTranspose2d(b*2,  b,    2, stride=2)
        self.dec1 = ConvBlock(b*2,  b)
        self.pool = nn.MaxPool2d(2)
        self.head = nn.Conv2d(b, out_ch, 1)

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool(e1))
        e3 = self.enc3(self.pool(e2))
        e4 = self.enc4(self.pool(e3))
        b  = self.bottleneck(self.pool(e4))
        d4 = self.dec4(torch.cat([self.up4(b),  e4], dim=1))
        d3 = self.dec3(torch.cat([self.up3(d4), e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d3), e2], dim=1))
        d1 = self.dec1(torch.cat([self.up1(d2), e1], dim=1))
        return self.head(d1)

class PatchGANDiscriminator(nn.Module):
    def __init__(self, in_ch=2):
        super().__init__()
        def block(ic, oc, stride=2, norm=True):
            layers = [nn.Conv2d(ic, oc, 4, stride=stride, padding=1, bias=not norm)]
            if norm:
                layers.append(nn.InstanceNorm2d(oc))
            layers.append(nn.LeakyReLU(0.2, inplace=True))
            return layers
        self.model = nn.Sequential(
            *block(in_ch, 64,  stride=2, norm=False),
            *block(64,    128, stride=2),
            *block(128,   256, stride=2),
            *block(256,   512, stride=1),
            nn.Conv2d(512, 1, 4, stride=1, padding=1),
        )
    def forward(self, mr, ct):
        return self.model(torch.cat([mr, ct], dim=1))

if CFG['model_type'] in ('unet', 'gan'):
    generator = UNet(CFG['in_ch'], CFG['out_ch'], CFG['unet_base_ch']).to(CFG['device'])
    n_params = sum(p.numel() for p in generator.parameters() if p.requires_grad)
    print(f'U-Net params: {n_params:,}')

if CFG['model_type'] == 'gan':
    discriminator = PatchGANDiscriminator(in_ch=2).to(CFG['device'])
    n_params_d = sum(p.numel() for p in discriminator.parameters() if p.requires_grad)
    print(f'PatchGAN params: {n_params_d:,}')

"""# 8.Loss func"""

def masked_l1(pred, target, mask):
    loss = torch.abs(pred - target)
    loss = loss * mask
    return loss.sum() / (mask.sum() + 1e-8)

def gan_generator_loss(disc_fake):
    return F.mse_loss(disc_fake, torch.ones_like(disc_fake))

def gan_discriminator_loss(disc_real, disc_fake):
    loss_real = F.mse_loss(disc_real, torch.ones_like(disc_real))
    loss_fake = F.mse_loss(disc_fake, torch.zeros_like(disc_fake))
    return (loss_real + loss_fake) * 0.5

print('Loss functions defined.')
print(f"Active loss: {CFG['loss_type']}")

"""# 9. Training"""

def run_validation(model, loader, device):
    model.eval()
    mae_list, ssim_list, psnr_list = [], [], []

    with torch.no_grad():
        for mr, ct, mask in tqdm(loader, desc='Validation', leave=False):
            mr, ct, mask = mr.to(device), ct.to(device), mask.to(device)
            pred = model(mr)

            pred_np = postprocess_ct(pred.cpu().numpy()[:, 0])   # (B, H, W) in HU
            ct_np   = postprocess_ct(ct.cpu().numpy()[:, 0])
            mask_np = mask.cpu().numpy()[:, 0]

            for b in range(pred_np.shape[0]):
                m = mask_np[b] > 0
                if m.sum() == 0:
                    continue
                mae  = np.abs(pred_np[b][m] - ct_np[b][m]).mean()
                data_range = ct_np[b][m].max() - ct_np[b][m].min()

                p_sl = pred_np[b].copy()
                c_sl = ct_np[b].copy()
                p_sl[~m] = 0
                c_sl[~m] = 0
                ssim = ssim_fn(c_sl, p_sl, data_range=float(data_range))
                psnr = psnr_fn(c_sl, p_sl, data_range=float(data_range))

                mae_list.append(mae)
                ssim_list.append(ssim)
                psnr_list.append(psnr)

    return {
        'mae':  float(np.mean(mae_list)),
        'ssim': float(np.mean(ssim_list)),
        'psnr': float(np.mean(psnr_list)),
    }

print('run_validation defined.')

opt_G = torch.optim.Adam(generator.parameters(), lr=CFG['lr'], betas=(0.5, 0.999))
if CFG['model_type'] == 'gan':
    opt_D = torch.optim.Adam(discriminator.parameters(), lr=CFG['lr'], betas=(0.5, 0.999))

history = {'train_loss': [], 'val_mae': [], 'val_ssim': [], 'val_psnr': []}

best_val_mae     = float('inf')
patience         = CFG.get('early_stopping_patience', 15)
patience_counter = 0
best_ckpt_path   = os.path.join(CFG['ckpt_dir'], 'best_model.pt')

for epoch in range(1, CFG['epochs'] + 1):
    generator.train()
    epoch_loss = 0.0

    for mr, ct, mask in tqdm(tr_loader, desc=f'Epoch {epoch}/{CFG["epochs"]}', leave=False):
        mr, ct, mask = mr.to(CFG['device']), ct.to(CFG['device']), mask.to(CFG['device'])
        pred = generator(mr)

        if CFG['loss_type'] == 'l1':
            loss = masked_l1(pred, ct, mask)
            opt_G.zero_grad()
            loss.backward()
            opt_G.step()

        elif CFG['loss_type'] == 'l1_gan':
            loss_l1     = masked_l1(pred, ct, mask)
            disc_fake   = discriminator(mr, pred)
            loss_g_gan  = gan_generator_loss(disc_fake)
            loss        = loss_l1 + 0.1 * loss_g_gan
            opt_G.zero_grad()
            loss.backward()
            opt_G.step()

            disc_real = discriminator(mr, ct)
            disc_fake = discriminator(mr, pred.detach())
            loss_d    = gan_discriminator_loss(disc_real, disc_fake)
            opt_D.zero_grad()
            loss_d.backward()
            opt_D.step()

        epoch_loss += loss.item()

    avg_loss = epoch_loss / len(tr_loader)
    history['train_loss'].append(avg_loss)

    if epoch % CFG['val_every'] == 0 or epoch == 1:
        val_metrics = run_validation(generator, hold_loader, CFG['device'])
        history['val_mae'].append(val_metrics['mae'])
        history['val_ssim'].append(val_metrics['ssim'])
        history['val_psnr'].append(val_metrics['psnr'])

        print(f"Epoch {epoch:03d} | loss {avg_loss:.4f} | "
              f"MAE {val_metrics['mae']:.4f} | "
              f"SSIM {val_metrics['ssim']:.4f} | "
              f"PSNR {val_metrics['psnr']:.2f}")

        if val_metrics['mae'] < best_val_mae:
            best_val_mae     = val_metrics['mae']
            patience_counter = 0
            torch.save({
                'epoch'       : epoch,
                'model_state' : generator.state_dict(),
                'opt_state'   : opt_G.state_dict(),
                'history'     : history,
                'best_val_mae': best_val_mae,
            }, best_ckpt_path)
            print(f'  Best model saved (MAE={best_val_mae:.4f})')
        else:
            patience_counter += 1
            print(f'  No improvement. Patience: {patience_counter}/{patience}')
            if patience_counter >= patience:
                print(f'Early stopping at epoch {epoch}.')
                break

    if epoch % CFG['save_every'] == 0:
        ckpt_path = os.path.join(CFG['ckpt_dir'], f'unet_epoch{epoch:03d}.pt')
        torch.save({
            'epoch'      : epoch,
            'model_state': generator.state_dict(),
            'opt_state'  : opt_G.state_dict(),
            'history'    : history,
        }, ckpt_path)
        print(f'  Checkpoint saved: {ckpt_path}')

print(f'Training complete. Best MAE: {best_val_mae:.4f}')

"""# 11.Visualisation"""

import matplotlib.pyplot as plt

def visualise_predictions(model, dataset, device, n=3):
    model.eval()
    indices = np.random.choice(len(dataset), n, replace=False)

    fig, axes = plt.subplots(n, 4, figsize=(16, 4 * n))
    if n == 1:
        axes = axes[np.newaxis, :]

    with torch.no_grad():
        for row, idx in enumerate(indices):
            mr, ct, mask = dataset[idx]
            pred = model(mr.unsqueeze(0).to(device)).cpu()

            mr_np   = mr.squeeze().numpy()
            ct_np   = postprocess_ct(ct.squeeze().numpy())
            pred_np = postprocess_ct(pred.squeeze().numpy())
            err_np  = np.abs(pred_np - ct_np) * mask.squeeze().numpy()

            axes[row, 0].imshow(mr_np,   cmap='gray');  axes[row, 0].set_title('MR input')
            axes[row, 1].imshow(ct_np,   cmap='gray');  axes[row, 1].set_title('CT real')
            axes[row, 2].imshow(pred_np, cmap='gray');  axes[row, 2].set_title('CT predicted')
            im = axes[row, 3].imshow(err_np, cmap='hot'); axes[row, 3].set_title('Abs error')
            plt.colorbar(im, ax=axes[row, 3])

            for ax in axes[row]:
                ax.axis('off')

    plt.tight_layout()
    plt.show()

visualise_predictions(generator, tr_dataset, CFG['device'], n=3)